modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="inetcore"
version="1.0.0"
displayName="inetcore"
updateJSONURL="https://github.com/FlamerMC/inetcore/blob/main/update.json"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="FlamerMC"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.inetcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.inetcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration